// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tynrzwqejtfefaersrii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5bnJ6d3FlanRmZWZhZXJzcmlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2OTAxNzUsImV4cCI6MjA2NzI2NjE3NX0.ACwLOmKBgkMpb5JR-GHVwrgs_nnUcfFVgG8LRidzk7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});